import{S as c,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();function f(s){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"43104791-fccc42375971f64c47e678deb",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(n).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const h=document.querySelector(".gallery"),p=new c(".gallery a",{captionsData:"alt"});function d(s){const o=s.map(({largeImageURL:n,webformatURL:t,tags:e,likes:r,views:i,comments:u,downloads:m})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${n}">
        <img class="photo" src="${t}" alt="${e}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${i}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${u}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${m}</p></li>
        </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",o),p.refresh()}const g=document.querySelector("form"),l=document.querySelector(".loader");function y(){l.classList.remove("is-hidden")}function L(){l.classList.add("is-hidden")}g.addEventListener("submit",async s=>{s.preventDefault();const o=s.target.elements.search.value.trim(),n=document.querySelector(".gallery");if(n.innerHTML="",y(),o===""){a.warning({color:"yellow",message:"Please fill in the field for search!",position:"topRight"});return}try{const t=await f(o);t.hits.length===0?a.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",position:"topRight"}):d(t.hits)}catch(t){console.log(t),a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}finally{L()}});document.addEventListener("DOMContentLoaded",()=>{new c(".gallery a").refresh()});
//# sourceMappingURL=commonHelpers.js.map
